

package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccountDirectory;
import Business.Student.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  Gamer
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    
    
     StudentDirectory vd;
    Enterprise enterprise;
    JPanel userProcessContainer;
    
    
    
     UserAccountDirectory user_Dir;
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,  StudentDirectory vd, UserAccountDirectory user_Dir) {
        
        
        initComponents();
        this.user_Dir =  user_Dir;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtManageUsre = new javax.swing.JButton();
        txtManageEmployee = new javax.swing.JButton();
        txtManageOrg = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 198, 103));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txtManageUsre.setBackground(new java.awt.Color(12, 36, 60));
        txtManageUsre.setForeground(new java.awt.Color(255, 255, 255));
        txtManageUsre.setText("Manage User");
        txtManageUsre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageUsreActionPerformed(evt);
            }
        });
        add(txtManageUsre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 190, -1));

        txtManageEmployee.setBackground(new java.awt.Color(12, 36, 60));
        txtManageEmployee.setForeground(new java.awt.Color(255, 255, 255));
        txtManageEmployee.setText("Manage Employee");
        txtManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageEmployeeActionPerformed(evt);
            }
        });
        add(txtManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 190, -1));

        txtManageOrg.setBackground(new java.awt.Color(12, 36, 60));
        txtManageOrg.setForeground(new java.awt.Color(255, 255, 255));
        txtManageOrg.setText("Manage Organization");
        txtManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageOrgActionPerformed(evt);
            }
        });
        add(txtManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 190, -1));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, 20));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText("Welcome!");
        jLabel7.setFocusable(false);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("Admin Work Area");
        jLabel8.setFocusable(false);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtManageUsreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageUsreActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_txtManageUsreActionPerformed

    private void txtManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageEmployeeActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_txtManageEmployeeActionPerformed

    private void txtManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageOrgActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_txtManageOrgActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton txtManageEmployee;
    private javax.swing.JButton txtManageOrg;
    private javax.swing.JButton txtManageUsre;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
