/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GradSchoolRole;

import Business.EcoSystem;
import Business.Student.Student;
import Business.Student.StudentDirectory;
import Business.WorkQueue.GradSchoolRequest;
import Business.WorkQueue.PartTimeRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sahitinallamolu
 */
public class ProcessGradReqJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessGradReqJPanel
     */
    
    GradSchoolRequest request;
    JPanel userProcessContainer;
    
    StudentDirectory vd;
    EcoSystem business;

    ProcessGradReqJPanel(JPanel userProcessContainer, GradSchoolRequest request, StudentDirectory vd, EcoSystem business) {
        
        this.request = request;
        this.vd = vd;
        this.userProcessContainer = userProcessContainer;
        
        this.business = business;
        initComponents();
        populateData();

    }

    void populateData() {
        txtHeader.setText("Review Applicant: " + request.getSender().getUsername());
        ArrayList<Business.Student.Student> vetDir = business.getVd().getStudent_Dir();
        System.out.println(vetDir);

        for (Student v : vetDir) {
            System.out.println(v);
            if (v.getUsername().equals(request.getSender().getUsername())) {
                txtVetID.setText("Student ID: " + v.getStudent_ID());
                txtAddress.setText("Address: " + v.getResidentAddress());
                txtGender.setText("Gender: " + v.getGender());
                txtMilType.setText("Student Branch: " + v.getArmyType());
                break;

            }
        }

        txtHS.setText(request.getHighSchool());
        txtHS1.setText(request.getHsGrade());
        txtHS2.setText(request.getBachUni());
        txtHS3.setText(request.getBachGrade());
        txtHS4.setText(request.getBachDegree());
        txtHS5.setText(request.getDesUni());
        txtHS6.setText(request.getDesProgram());
        txtHS7.setText(request.getDesIntake());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHeader = new javax.swing.JLabel();
        txtVetID = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        txtMilType = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtHS = new javax.swing.JLabel();
        txtHS1 = new javax.swing.JLabel();
        txtHS2 = new javax.swing.JLabel();
        txtHS3 = new javax.swing.JLabel();
        txtHS4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHS5 = new javax.swing.JLabel();
        txtHS6 = new javax.swing.JLabel();
        txtHS7 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 198, 103));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHeader.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtHeader.setFocusable(false);
        add(txtHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 357, 32));

        txtVetID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtVetID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 23));

        txtGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 23));

        txtMilType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtMilType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, 23));

        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 23));

        btnBack.setBackground(new java.awt.Color(12, 36, 60));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 100, -1));

        txtHS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 272, 26));

        txtHS1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 272, 26));

        txtHS2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 272, 26));

        txtHS3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 272, 26));

        txtHS4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 272, 26));

        jLabel1.setText("Applicant Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel2.setText("Seeking Admission for:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel3.setText("Bachelor's Degree Information");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        txtHS5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 272, 26));

        txtHS6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 272, 26));

        txtHS7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtHS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 272, 26));

        btnAccept.setBackground(new java.awt.Color(12, 36, 60));
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 130, 40));

        btnReject.setBackground(new java.awt.Color(12, 36, 60));
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 130, 40));

        jLabel4.setText("High School Information");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GradSchoolWorkAreaJPanel dwjp = (GradSchoolWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed

        request.setStatus("Accepted");
        JOptionPane.showMessageDialog(null, "Candidate: " + request.getSender().getUsername() + " Accepted. Status will be updated accordingly.", "Information", JOptionPane.INFORMATION_MESSAGE);
        btnAccept.setEnabled(false);
        btnReject.setEnabled(false);

        

    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        request.setStatus("Rejected");
        JOptionPane.showMessageDialog(null, "Candidate: " + request.getSender().getUsername() + " Rejected. Status will be updated accordingly.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        btnReject.setEnabled(false);
        btnAccept.setEnabled(false);

       
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtHS;
    private javax.swing.JLabel txtHS1;
    private javax.swing.JLabel txtHS2;
    private javax.swing.JLabel txtHS3;
    private javax.swing.JLabel txtHS4;
    private javax.swing.JLabel txtHS5;
    private javax.swing.JLabel txtHS6;
    private javax.swing.JLabel txtHS7;
    private javax.swing.JLabel txtHeader;
    private javax.swing.JLabel txtMilType;
    private javax.swing.JLabel txtVetID;
    // End of variables declaration//GEN-END:variables
}
