/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Listings.TempHouseListing;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PermHousingOrganization;
import Business.Organization.TempHousingOrganization;
import Business.UserAccount.UserAccount;
import Business.Student.StudentDirectory;
import Business.WorkQueue.TempHousingRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sahitinallamolu
 */
public class RequestTempHousingJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private StudentDirectory vd;
    private EcoSystem system;
    private Enterprise enterprise;


    /**
     * Creates new form RequestTempHousingJPanel
     */
    public RequestTempHousingJPanel(JPanel userProcessContainer, UserAccount userAccount, StudentDirectory vd, EcoSystem system) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        
        
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.vd = vd;
        this.system = system;
        
        
        populateHousingComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        housingSocietyComboBox = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        NumberComboBox = new javax.swing.JComboBox<String>();
        btnRequest = new javax.swing.JButton();
        txtMessage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 198, 103));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Number Of Members: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        add(housingSocietyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 231, -1));

        jLabel2.setText("Society : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        NumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "1", "2", "3", "4", "5", "6" }));
        add(NumberComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 231, -1));

        btnRequest.setBackground(new java.awt.Color(12, 36, 60));
        btnRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 130, 40));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 231, 40));

        jLabel4.setText("Message:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        btnback.setBackground(new java.awt.Color(12, 36, 60));
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 100, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Temporary Housing");
        jLabel5.setFocusable(false);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        TempHousingRequest tr = new TempHousingRequest();
        
        
        
        tr.setSender(userAccount);
        tr.setStatus("Sent");
        tr.setMessage(txtMessage.getText());
        tr.setHousingSociety((String) housingSocietyComboBox.getSelectedItem());
        tr.setNumberOfPeople(Integer.parseInt((String) NumberComboBox.getSelectedItem()));
        Organization org = null;
        
        
        

        for (Network network : system.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);

                //Step 3:check against each organization for each enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof TempHousingOrganization) {
                        org = organization;
                        break;
                    }

                }
            }
        }
        
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(tr);
            System.out.println("Added Request to Org ");
            userAccount.getWorkQueue().getWorkRequestList().add(tr);
            System.out.println("Added Request to UserAccount ");

    }//GEN-LAST:event_btnRequestActionPerformed
    JOptionPane.showMessageDialog(null, "Request Has Been Raised. You will be notified accordingly.", "Warning", JOptionPane.WARNING_MESSAGE);
    btnRequest.setEnabled(false);
    txtMessage.setText("");
    txtMessage.setEnabled(false);
    NumberComboBox.setEnabled(false);
    housingSocietyComboBox.setEnabled(false);
            
    }
    
    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        
        
        userProcessContainer.remove(this);
        
        
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        
        
        StudentWorkAreaJPanel dwjp = (StudentWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnbackActionPerformed

    private void populateHousingComboBox() {
        
        
        for (TempHouseListing th : system.getThsd().getTempHouseListing_Dir()) {
            housingSocietyComboBox.addItem(th.getHousingSociety());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> NumberComboBox;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> housingSocietyComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
